workspace:
  base: /mytop

kind: pipeline
name: build

steps:
- name: build
  image: golang:1.15
  pull: always
  environment:
    CGO_ENABLED: 0
    CI: circleci
  commands:
  - make test
  - make build
